releases:
  versioned:
    tag_specs:
    - '{ubuntu}{intel-python}{xgboost}'
slice_sets:
  xgboost:
  - add_to_name: xgboost
    args:
    - UBUNTU_VERSION=20.04
    - MINICONDA_VERSION=4.7.12
    dockerfile_subdirectory: ml/XGBoost
    partials:
    - ml/xgboost
