releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{language-modeling}{mpi-horovod}{bert-large-bfloat16-training}'
slice_sets:
  bert-large-bfloat16-training:
  - add_to_name: -bert-large-bfloat16-training
    args:
    - PACKAGE_NAME=bert-large-bfloat16-training
    dockerfile_subdirectory: model_containers
    documentation:
      docs:
      - name: Title
        uri: models/quickstart/language_modeling/tensorflow/bert_large/training/bfloat16/.docs/title.md
      - name: Description
        uri: models/quickstart/language_modeling/tensorflow/bert_large/training/bfloat16/.docs/description.md
      - name: Download link
        uri: models/quickstart/language_modeling/tensorflow/bert_large/training/bfloat16/.docs/download.md
      - name: Datasets
        uri: models/quickstart/language_modeling/tensorflow/bert_large/training/bfloat16/.docs/datasets.md
      - name: Quick Start Scripts
        uri: models/quickstart/language_modeling/tensorflow/bert_large/training/bfloat16/.docs/quickstart.md
      - name: Bare Metal
        uri: models/quickstart/language_modeling/tensorflow/bert_large/training/bfloat16/.docs/baremetal.md
      - name: Docker
        uri: models/quickstart/language_modeling/tensorflow/bert_large/training/bfloat16/.docs/docker.md
      - name: License
        uri: models/quickstart/language_modeling/tensorflow/bert_large/training/bfloat16/.docs/license.md
      name: README.md
      text_replace:
        <docker image>: 'intel/language-modeling:tf-2.3.0-imz-2.2.0-bert-large-bfloat16-training'
        <mode>: training
        <model name>: BERT Large
        <package dir>: bert-large-bfloat16-training
        <package name>: bert-large-bfloat16-training.tar.gz
        <package url>: 'https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_2_0/bert-large-bfloat16-training.tar.gz'
        <precision>: BFloat16
        <use case>: language_modeling
      uri: models/quickstart/language_modeling/tensorflow/bert_large/training/bfloat16
    downloads: []
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/language_modeling/tensorflow/bert_large/README.md
      source: benchmarks/language_modeling/tensorflow/bert_large/README.md
    - destination: benchmarks/language_modeling/tensorflow/bert_large/__init__.py
      source: benchmarks/language_modeling/tensorflow/bert_large/__init__.py
    - destination: benchmarks/language_modeling/tensorflow/bert_large/training/bfloat16
      source: benchmarks/language_modeling/tensorflow/bert_large/training/bfloat16
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/language_modeling/tensorflow/bert_large/training/bfloat16
      source: models/language_modeling/tensorflow/bert_large/training/bfloat16
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/language_modeling/tensorflow/bert_large/training/bfloat16
    partials:
    - python-build
    - model_package
    - entrypoint
