releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{language-translation}{mlperf-gnmt-fp32-inference}'
slice_sets:
  mlperf-gnmt-fp32-inference:
  - add_to_name: -mlperf-gnmt-fp32-inference
    args:
    - PACKAGE_NAME=mlperf-gnmt-fp32-inference
    dockerfile_subdirectory: model_containers
    documentation:
      docs:
      - name: Title
        uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/fp32/.docs/title.md
      - name: Description
        uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/fp32/.docs/description.md
      - name: Download link
        uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/fp32/.docs/download.md
      - name: Datasets
        uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/fp32/.docs/datasets.md
      - name: Quick Start Scripts
        uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/fp32/.docs/quickstart.md
      - name: Bare Metal
        uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/fp32/.docs/baremetal.md
      - name: Docker
        uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/fp32/.docs/docker.md
      - name: License
        uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/fp32/.docs/license.md
      name: README.md
      text_replace:
        <docker image>: 'intel/language-translation:tf-2.3.0-imz-2.2.0-mlperf-gnmt-fp32-inference'
        <mode>: inference
        <model name>: MLPerf GNMT
        <package dir>: mlperf-gnmt-fp32-inference
        <package name>: mlperf-gnmt-fp32-inference.tar.gz
        <package url>: 'https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_2_0/mlperf-gnmt-fp32-inference.tar.gz'
        <precision>: FP32
        <use case>: language_translation
      uri: models/quickstart/language_translation/tensorflow/mlperf_gnmt/inference/fp32
    downloads:
    - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_8/mlperf_gnmt_fp32_pretrained_model.pb
      destination: mlperf_gnmt_fp32_pretrained_model.pb
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/language_translation/__init__.py
      source: benchmarks/language_translation/__init__.py
    - destination: benchmarks/language_translation/tensorflow/__init__.py
      source: benchmarks/language_translation/tensorflow/__init__.py
    - destination: benchmarks/language_translation/tensorflow/mlperf_gnmt/README.md
      source: benchmarks/language_translation/tensorflow/mlperf_gnmt/README.md
    - destination: benchmarks/language_translation/tensorflow/mlperf_gnmt/__init__.py
      source: benchmarks/language_translation/tensorflow/mlperf_gnmt/__init__.py
    - destination: benchmarks/language_translation/tensorflow/mlperf_gnmt/inference/__init__.py
      source: benchmarks/language_translation/tensorflow/mlperf_gnmt/inference/__init__.py
    - destination: benchmarks/language_translation/tensorflow/mlperf_gnmt/inference/fp32
      source: benchmarks/language_translation/tensorflow/mlperf_gnmt/inference/fp32
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/language_translation/tensorflow/mlperf_gnmt/fp32
      source: models/language_translation/tensorflow/mlperf_gnmt/fp32
    - destination: models/language_translation/tensorflow/mlperf_gnmt/gnmt-v0.5.2.patch
      source: models/language_translation/tensorflow/mlperf_gnmt/gnmt-v0.5.2.patch
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/language_translation/tensorflow/mlperf_gnmt/inference/fp32
    partials:
    - model_package
    - language_translation/mlperf_gnmt_tf_addons
    - entrypoint
