releases:
  tf_1.15.2_containers:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{recommendation}{ncf-fp32-inference}'
slice_sets:
  ncf-fp32-inference:
  - add_to_name: -ncf-fp32-inference
    args:
    - TENSORFLOW_TAG=1.15.2
    - TF_MODELS_BRANCH=r1.11
    - PACKAGE_NAME=ncf-fp32-inference
    dockerfile_subdirectory: model_containers
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/title.md
        - name: Description
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/description.md
        - name: Download link
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/download.md
        - name: Datasets
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/baremetal.md
        - name: Docker
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/docker.md
        - name: License
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/license.md
        name: README.md
        text_replace:
          <docker image>: intel/recommendation:tf-1.15.2-ncf-fp32-inference
          <mode>: inference
          <model name>: NCF
          <package dir>: ncf-fp32-inference
          <package name>: ncf-fp32-inference.tar.gz
          <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_7_0/ncf-fp32-inference.tar.gz
          <precision>: FP32
          <use case>: recommendation
        uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32
      - docs:
        - name: Title
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/title.md
        - name: Description
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/description.md
        - name: Datasets
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32/.docs/aikit.md
        - name: Resources
          uri: models/quickstart/common/.docs/resources_with_portal_link.md
        name: README.md
        text_replace:
          <mode>: inference
          <model name>: NCF
          <precision>: FP32
          <use case>: recommendation
          <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/ncf-fp32-inference-tensorflow-container.html
        uri: models/benchmarks/recommendation/tensorflow/ncf/inference/fp32
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/recommendation/tensorflow/ncf/inference/fp32/.docs/advanced/launch_benchmark_instructions.md
        name: Advanced.md
        text_replace:
          <mode>: inference
          <model name>: NCF
          <precision>: FP32
          <use case>: recommendation
          <docker image>: intel/intel-optimized-tensorflow:1.15.2
        uri: models/benchmarks/recommendation/tensorflow/ncf/inference/fp32
    downloads:
    - destination: pretrained_model/ncf_fp32_pretrained_model.tar.gz
      source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_5/ncf_fp32_pretrained_model.tar.gz
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: benchmarks/recommendation/__init__.py
      source: benchmarks/recommendation/__init__.py
    - destination: benchmarks/recommendation/tensorflow/__init__.py
      source: benchmarks/recommendation/tensorflow/__init__.py
    - destination: benchmarks/recommendation/tensorflow/ncf/README.md
      source: benchmarks/recommendation/tensorflow/ncf/README.md
    - destination: benchmarks/recommendation/tensorflow/ncf/__init__.py
      source: benchmarks/recommendation/tensorflow/ncf/__init__.py
    - destination: benchmarks/recommendation/tensorflow/ncf/inference/__init__.py
      source: benchmarks/recommendation/tensorflow/ncf/inference/__init__.py
    - destination: benchmarks/recommendation/tensorflow/ncf/inference/fp32
      source: benchmarks/recommendation/tensorflow/ncf/inference/fp32
    - destination: models/common
      source: models/common
    - destination: models/recommendation/tensorflow/ncf/inference/fp32
      source: models/recommendation/tensorflow/ncf/inference/fp32
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/recommendation/tensorflow/ncf/inference/cpu/fp32
    partials:
    - tensorflow/model-source
    - recommendation/ncf_pip_installs
    - model_package
    - tar
    - entrypoint
