releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{image-recognition}{resnet50v1-5-bfloat16-inference}'
slice_sets:
  resnet50v1-5-bfloat16-inference:
  - add_to_name: -resnet50v1-5-bfloat16-inference
    args:
    - PACKAGE_NAME=resnet50v1-5-bfloat16-inference
    dockerfile_subdirectory: model_containers
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/title.md
        - name: Description
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/description.md
        - name: Download link
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/download.md
        - name: Datasets
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/baremetal.md
        - name: Docker
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/docker.md
        - name: License
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/license.md
        name: README.md
        text_replace:
          <docker image>: intel/image-recognition:tf-latest-resnet50v1-5-bfloat16-inference
          <mode>: inference
          <model name>: ResNet50 v1.5
          <package dir>: resnet50v1_5-bfloat16-inference
          <package name>: resnet50v1_5-bfloat16-inference.tar.gz
          <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_7_0/resnet50v1-5-bfloat16-inference.tar.gz
          <precision>: BFloat16
          <use case>: image_recognition
        uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16
      - docs:
        - name: Title
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/title.md
        - name: Description
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/description.md
        - name: Datasets
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/quickstart.md
        - name: AI Kit
          uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16/.docs/aikit.md
        - name: Resources
          uri: models/quickstart/common/.docs/resources_with_portal_link.md
        name: README.md
        text_replace:
          <mode>: inference
          <model name>: ResNet50 v1.5
          <precision>: BFloat16
          <use case>: image_recognition
          <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/resnet50v1-5-bfloat16-inference-tensorflow-container.html
        uri: models/benchmarks/image_recognition/tensorflow/resnet50v1_5/inference/bfloat16
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/image_recognition/tensorflow/resnet50v1_5/inference/bfloat16/.docs/advanced/launch_benchmark_instructions.md
        name: Advanced.md
        text_replace:
          <mode>: inference
          <model name>: ResNet50 v1.5
          <precision>: BFloat16
          <use case>: image_recognition
          <docker image>: intel/intel-optimized-tensorflow:latest
        uri: models/benchmarks/image_recognition/tensorflow/resnet50v1_5/inference/bfloat16
    downloads:
    - destination: resnet50_v1_5_bfloat16.pb
      source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_8/resnet50_v1_5_bfloat16.pb
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/image_recognition/__init__.py
      source: benchmarks/image_recognition/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/__init__.py
      source: benchmarks/image_recognition/tensorflow/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/resnet50v1_5/README.md
      source: benchmarks/image_recognition/tensorflow/resnet50v1_5/README.md
    - destination: benchmarks/image_recognition/tensorflow/resnet50v1_5/__init__.py
      source: benchmarks/image_recognition/tensorflow/resnet50v1_5/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/resnet50v1_5/inference/__init__.py
      source: benchmarks/image_recognition/tensorflow/resnet50v1_5/inference/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/resnet50v1_5/inference/bfloat16
      source: benchmarks/image_recognition/tensorflow/resnet50v1_5/inference/bfloat16
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/image_recognition/tensorflow/resnet50v1_5/inference
      source: models/image_recognition/tensorflow/resnet50v1_5/inference
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/image_recognition/tensorflow/resnet50v1_5/inference/cpu/bfloat16
    partials:
    - model_package
    - entrypoint
