releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{image-recognition}{resnet50-int8-inference}'
slice_sets:
  resnet50-int8-inference:
  - add_to_name: -resnet50-int8-inference
    args:
    - PACKAGE_NAME=resnet50-int8-inference
    dockerfile_subdirectory: model_containers
    documentation:
      docs:
      - name: Title
        uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/int8/.docs/title.md
      - name: Description
        uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/int8/.docs/description.md
      - name: Download link
        uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/int8/.docs/download.md
      - name: Datasets
        uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/int8/.docs/datasets.md
      - name: Quick Start Scripts
        uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/int8/.docs/quickstart.md
      - name: Bare Metal
        uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/int8/.docs/baremetal.md
      - name: Docker
        uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/int8/.docs/docker.md
      - name: License
        uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/int8/.docs/license.md
      name: README.md
      text_replace:
        <docker image>: intel/image-recognition:tf-2.3.0-imz-2.2.0-resnet50-int8-inference
        <mode>: inference
        <model name>: ResNet50
        <package dir>: resnet50-int8-inference
        <package name>: resnet50-int8-inference.tar.gz
        <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_2_0/resnet50-int8-inference.tar.gz
        <precision>: Int8
        <use case>: image_recognition
      uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/int8
    downloads:
    - destination: resnet50_int8_pretrained_model.pb
      source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_8/resnet50_int8_pretrained_model.pb
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/image_recognition/__init__.py
      source: benchmarks/image_recognition/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/__init__.py
      source: benchmarks/image_recognition/tensorflow/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/resnet50/README.md
      source: benchmarks/image_recognition/tensorflow/resnet50/README.md
    - destination: benchmarks/image_recognition/tensorflow/resnet50/__init__.py
      source: benchmarks/image_recognition/tensorflow/resnet50/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/resnet50/inference/__init__.py
      source: benchmarks/image_recognition/tensorflow/resnet50/inference/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/resnet50/inference/int8
      source: benchmarks/image_recognition/tensorflow/resnet50/inference/int8
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/image_recognition/tensorflow/resnet50/inference
      source: models/image_recognition/tensorflow/resnet50/inference
    - destination: models/image_recognition/tensorflow/resnet50/int8
      source: models/image_recognition/tensorflow/resnet50/int8
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/image_recognition/tensorflow/resnet50/inference/int8
    partials:
    - model_package
    - entrypoint
