releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{object-detection}{rfcn-int8-inference}'
slice_sets:
  rfcn-int8-inference:
  - add_to_name: -rfcn-int8-inference
    args:
    - PACKAGE_NAME=rfcn-int8-inference
    - TF_MODELS_BRANCH=6c21084503b27a9ab118e1db25f79957d5ef540b
    dockerfile_subdirectory: model_containers
    documentation:
      docs:
      - name: Title
        uri: models/quickstart/object_detection/tensorflow/rfcn/inference/int8/.docs/title.md
      - name: Description
        uri: models/quickstart/object_detection/tensorflow/rfcn/inference/int8/.docs/description.md
      - name: Download link
        uri: models/quickstart/object_detection/tensorflow/rfcn/inference/int8/.docs/download.md
      - name: Datasets
        uri: models/quickstart/object_detection/tensorflow/rfcn/inference/int8/.docs/datasets.md
      - name: Quick Start Scripts
        uri: models/quickstart/object_detection/tensorflow/rfcn/inference/int8/.docs/quickstart.md
      - name: Bare Metal
        uri: models/quickstart/object_detection/tensorflow/rfcn/inference/int8/.docs/baremetal.md
      - name: Docker
        uri: models/quickstart/object_detection/tensorflow/rfcn/inference/int8/.docs/docker.md
      - name: License
        uri: models/quickstart/object_detection/tensorflow/rfcn/inference/int8/.docs/license.md
      name: README.md
      text_replace:
        <docker image>: intel/object-detection:tf-2.3.0-imz-2.2.0-rfcn-int8-inference
        <mode>: inference
        <model name>: RFCN
        <package dir>: rfcn-int8-inference
        <package name>: rfcn-int8-inference.tar.gz
        <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_2_0/rfcn-int8-inference.tar.gz
        <precision>: Int8
        <use case>: object_detection
      uri: models/quickstart/object_detection/tensorflow/rfcn/inference/int8
    downloads:
    - destination: rfcn_resnet101_int8_coco_pretrained_model.pb
      source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_8/rfcn_resnet101_int8_coco_pretrained_model.pb
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: benchmarks/object_detection/__init__.py
      source: benchmarks/object_detection/__init__.py
    - destination: benchmarks/object_detection/tensorflow/__init__.py
      source: benchmarks/object_detection/tensorflow/__init__.py
    - destination: benchmarks/object_detection/tensorflow/rfcn/README.md
      source: benchmarks/object_detection/tensorflow/rfcn/README.md
    - destination: benchmarks/object_detection/tensorflow/rfcn/__init__.py
      source: benchmarks/object_detection/tensorflow/rfcn/__init__.py
    - destination: benchmarks/object_detection/tensorflow/rfcn/inference/__init__.py
      source: benchmarks/object_detection/tensorflow/rfcn/inference/__init__.py
    - destination: benchmarks/object_detection/tensorflow/rfcn/inference/int8
      source: benchmarks/object_detection/tensorflow/rfcn/inference/int8
    - destination: models/common
      source: models/common
    - destination: models/object_detection/tensorflow/rfcn/inference/int8
      source: models/object_detection/tensorflow/rfcn/inference/int8
    - destination: models/object_detection/tensorflow/rfcn/inference/tf-2.0.patch
      source: models/object_detection/tensorflow/rfcn/inference/tf-2.0.patch
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/object_detection/tensorflow/rfcn/inference/int8
    partials:
    - model_package
    - object_detection/rfcn_patch
    - tar
    - entrypoint
