releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{object-detection}{ssd-resnet34-fp32-inference}'
slice_sets:
  ssd-resnet34-fp32-inference:
  - add_to_name: -ssd-resnet34-fp32-inference
    args:
    - TENSORFLOW_IMAGE=intel/intel-optimized-tensorflow
    - PACKAGE_NAME=ssd-resnet34-fp32-inference
    - TF_BENCHMARKS_BRANCH=509b9d288937216ca7069f31cfb22aaa7db6a4a7
    - TF_BENCHMARKS_DIR=/tensorflow/ssd-resnet-benchmarks
    - TF_MODELS_BRANCH=f505cecde2d8ebf6fe15f40fb8bc350b2b1ed5dc
    dockerfile_subdirectory: model_containers
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/title.md
        - name: Description
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/description.md
        - name: Download link
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/download.md
        - name: Datasets
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/baremetal.md
        - name: Docker
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/docker.md
        - name: Advanced Options
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/advancedoptions.md
        - name: License
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/license.md
        name: README.md
        text_replace:
          <mode>: inference
          <model name>: SSD-ResNet34
          <precision>: FP32
          <use case>: object_detection
          <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_7_0/ssd-resnet34-fp32-inference.tar.gz
          <package name>: ssd-resnet34-fp32-inference.tar.gz
          <package dir>: ssd-resnet34-fp32-inference
          <docker image>: intel/object-detection:tf-latest-ssd-resnet34-fp32-inference
        uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32
      - docs:
        - name: Title
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/title.md
        - name: Description
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/description.md
        - name: Datasets
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/quickstart.md
        - name: AI Kit
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32/.docs/aikit.md
        - name: Resources
          uri: models/quickstart/common/.docs/resources_with_portal_link.md
        name: README.md
        text_replace:
          <mode>: inference
          <model name>: SSD-ResNet34
          <precision>: FP32
          <use case>: object_detection
          <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/ssd-resnet34-fp32-inference-tensorflow-container.html
        uri: models/benchmarks/object_detection/tensorflow/ssd-resnet34/inference/fp32
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/object_detection/tensorflow/ssd-resnet34/inference/fp32/.docs/advanced/launch_benchmark_instructions.md
        name: Advanced.md
        text_replace:
          <mode>: inference
          <model name>: SSD-ResNet34
          <precision>: FP32
          <use case>: object_detection
          <docker image>: 'intel/intel-optimized-tensorflow:latest'
        uri: models/benchmarks/object_detection/tensorflow/ssd-resnet34/inference/fp32
    downloads:
    - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_6/ssd_resnet34_fp32_bs1_pretrained_model.pb
      destination: pretrained_model/ssd_resnet34_fp32_bs1_pretrained_model.pb
    - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/ssd_resnet34_fp32_1200x1200_pretrained_model.pb
      destination: pretrained_model/ssd_resnet34_fp32_1200x1200_pretrained_model.pb
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: benchmarks/object_detection/__init__.py
      source: benchmarks/object_detection/__init__.py
    - destination: benchmarks/object_detection/tensorflow/__init__.py
      source: benchmarks/object_detection/tensorflow/__init__.py
    - destination: benchmarks/object_detection/tensorflow/ssd-resnet34/README.md
      source: benchmarks/object_detection/tensorflow/ssd-resnet34/README.md
    - destination: benchmarks/object_detection/tensorflow/ssd-resnet34/__init__.py
      source: benchmarks/object_detection/tensorflow/ssd-resnet34/__init__.py
    - destination: benchmarks/object_detection/tensorflow/ssd-resnet34/inference/__init__.py
      source: benchmarks/object_detection/tensorflow/ssd-resnet34/inference/__init__.py
    - destination: benchmarks/object_detection/tensorflow/ssd-resnet34/inference/fp32
      source: benchmarks/object_detection/tensorflow/ssd-resnet34/inference/fp32
    - destination: models/common
      source: models/common
    - destination: models/object_detection/tensorflow/ssd-resnet34/inference/fp32
      source: models/object_detection/tensorflow/ssd-resnet34/inference/fp32
    - destination: models/object_detection/tensorflow/ssd-resnet34/inference/tensorflow_benchmarks_tf2.0.patch
      source: models/object_detection/tensorflow/ssd-resnet34/inference/tensorflow_benchmarks_tf2.0.patch
    - destination: models/object_detection/tensorflow/ssd-resnet34/inference/tensorflow_models_tf2.0.patch
      source: models/object_detection/tensorflow/ssd-resnet34/inference/tensorflow_models_tf2.0.patch
    - destination: models/object_detection/tensorflow/ssd-resnet34/inference/tf_benchmarks.patch
      source: models/object_detection/tensorflow/ssd-resnet34/inference/tf_benchmarks.patch
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/fp32
    partials:
    - numactl
    - libgl
    - opencv
    - tensorflow-addons-0.11.0
    - tensorflow/benchmarks-source
    - model_package
    - entrypoint
