releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{language-translation}{mpi-horovod}{transformer-mlperf-fp32-training}'
slice_sets:
  transformer-mlperf-fp32-training:
  - add_to_name: -transformer-mlperf-fp32-training
    args:
    - PACKAGE_NAME=transformer-mlperf-fp32-training
    dockerfile_subdirectory: model_containers
    documentation:
      docs:
      - name: Title
        uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/fp32/.docs/title.md
      - name: Description
        uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/fp32/.docs/description.md
      - name: Download link
        uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/fp32/.docs/download.md
      - name: Datasets
        uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/fp32/.docs/datasets.md
      - name: Quick Start Scripts
        uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/fp32/.docs/quickstart.md
      - name: Bare Metal
        uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/fp32/.docs/baremetal.md
      - name: Docker
        uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/fp32/.docs/docker.md
      - name: License
        uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/fp32/.docs/license.md
      name: README.md
      text_replace:
        <docker image>: intel/language-translation:tf-2.3.0-imz-2.2.0-transformer-mlperf-fp32-training
        <mode>: training
        <model name>: Transformer Language
        <package dir>: transformer-mlperf-fp32-training
        <package name>: transformer-mlperf-fp32-training.tar.gz
        <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_2_0/transformer-mlperf-fp32-training.tar.gz
        <precision>: FP32
        <use case>: language_translation
      uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/fp32
    downloads: []
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/language_translation/__init__.py
      source: benchmarks/language_translation/__init__.py
    - destination: benchmarks/language_translation/tensorflow/__init__.py
      source: benchmarks/language_translation/tensorflow/__init__.py
    - destination: benchmarks/language_translation/tensorflow/transformer_mlperf/README.md
      source: benchmarks/language_translation/tensorflow/transformer_mlperf/README.md
    - destination: benchmarks/language_translation/tensorflow/transformer_mlperf/training/__init__.py
      source: benchmarks/language_translation/tensorflow/transformer_mlperf/training/__init__.py
    - destination: benchmarks/language_translation/tensorflow/transformer_mlperf/training/fp32
      source: benchmarks/language_translation/tensorflow/transformer_mlperf/training/fp32
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/language_translation/tensorflow/transformer_mlperf/training/fp32
      source: models/language_translation/tensorflow/transformer_mlperf/training/fp32
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/language_translation/tensorflow/transformer_mlperf/training/fp32
    partials:
    - model_package
    - entrypoint
