releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{language-translation}{mpi-horovod}{transformer-mlperf-bfloat16-training}'
slice_sets:
  transformer-mlperf-bfloat16-training:
  - add_to_name: -transformer-mlperf-bfloat16-training
    args:
    - PACKAGE_NAME=transformer-mlperf-bfloat16-training
    dockerfile_subdirectory: model_containers
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/title.md
        - name: Description
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/description.md
        - name: Download link
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/download.md
        - name: Datasets
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/baremetal.md
        - name: Docker
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/docker.md
        - name: License
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/license.md
        name: README.md
        text_replace:
          <docker image>: 'intel/language-translation:tf-latest-transformer-mlperf-bfloat16-training'
          <mode>: training
          <model name>: Transformer Language
          <package dir>: transformer-mlperf-bfloat16-training
          <package name>: transformer-mlperf-bfloat16-training.tar.gz
          <package url>: 'https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_6_0/transformer-mlperf-bfloat16-training.tar.gz'
          <precision>: BFloat16
          <use case>: language_translation
        uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16
      - docs:
        - name: Title
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/title.md
        - name: Description
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/description.md
        - name: Datasets
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/aikit_datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/quickstart.md
        - name: AI Kit
          uri: models/quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16/.docs/aikit.md
        - name: Resources
          uri: models/quickstart/common/.docs/resources_with_portal_link.md
        name: README.md
        text_replace:
          <mode>: training
          <model name>: Transformer Language
          <precision>: BFloat16
          <use case>: language_translation
          <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/transformer-lt-mlperf-bfloat16-training-tensorflow-container.html
        uri: models/benchmarks/language_translation/tensorflow/transformer_mlperf/training/bfloat16
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/language_translation/tensorflow/transformer_mlperf/training/bfloat16/.docs/advanced/launch_benchmark_instructions.md
        name: Advanced.md
        text_replace:
          <mode>: training
          <model name>: Transformer Language
          <precision>: BFloat16
          <use case>: language_translation
          <docker image>: intel/intel-optimized-tensorflow:latest
        uri: models/benchmarks/language_translation/tensorflow/transformer_mlperf/training/bfloat16
    downloads: []
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/language_translation/__init__.py
      source: benchmarks/language_translation/__init__.py
    - destination: benchmarks/language_translation/tensorflow/__init__.py
      source: benchmarks/language_translation/tensorflow/__init__.py
    - destination: benchmarks/language_translation/tensorflow/transformer_mlperf/README.md
      source: benchmarks/language_translation/tensorflow/transformer_mlperf/README.md
    - destination: benchmarks/language_translation/tensorflow/transformer_mlperf/training/__init__.py
      source: benchmarks/language_translation/tensorflow/transformer_mlperf/training/__init__.py
    - destination: benchmarks/language_translation/tensorflow/transformer_mlperf/training/bfloat16
      source: benchmarks/language_translation/tensorflow/transformer_mlperf/training/bfloat16
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/language_translation/tensorflow/transformer_mlperf/training/bfloat16
      source: models/language_translation/tensorflow/transformer_mlperf/training/bfloat16
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/language_translation/tensorflow/transformer_mlperf/training/cpu/bfloat16
    partials:
    - model_package
    - entrypoint
