releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{recommendation}{wide-deep-large-ds-fp32-training}'
slice_sets:
  wide-deep-large-ds-fp32-training:
  - add_to_name: -wide-deep-large-ds-fp32-training
    args:
    - PACKAGE_NAME=wide-deep-large-ds-fp32-training
    dockerfile_subdirectory: model_containers
    downloads: []
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: benchmarks/recommendation/__init__.py
      source: benchmarks/recommendation/__init__.py
    - destination: benchmarks/recommendation/tensorflow/__init__.py
      source: benchmarks/recommendation/tensorflow/__init__.py
    - destination: benchmarks/recommendation/tensorflow/wide_deep_large_ds/README.md
      source: benchmarks/recommendation/tensorflow/wide_deep_large_ds/README.md
    - destination: benchmarks/recommendation/tensorflow/wide_deep_large_ds/__init__.py
      source: benchmarks/recommendation/tensorflow/wide_deep_large_ds/__init__.py
    - destination: benchmarks/recommendation/tensorflow/wide_deep_large_ds/training/__init__.py
      source: benchmarks/recommendation/tensorflow/wide_deep_large_ds/training/__init__.py
    - destination: benchmarks/recommendation/tensorflow/wide_deep_large_ds/training/fp32
      source: benchmarks/recommendation/tensorflow/wide_deep_large_ds/training/fp32
    - destination: models/common
      source: models/common
    - destination: models/recommendation/tensorflow/wide_deep_large_ds/training
      source: models/recommendation/tensorflow/wide_deep_large_ds/training
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/recommendation/tensorflow/wide_deep_large_ds/training/fp32
    partials:
    - model_package
    - entrypoint
    documentation:
      name: README.md
      uri: models/quickstart/recommendation/tensorflow/wide_deep_large_ds/training/fp32
      text_replace:
        <mode>: training
        <model name>: Wide and Deep Large Dataset
        <precision>: FP32
        <use case>: recommendation
        <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_2_0/wide-deep-large-ds-fp32-training.tar.gz
        <package name>: wide-deep-large-ds-fp32-training.tar.gz
        <package dir>: wide-deep-large-ds-fp32-training
        <docker image>: intel/recommendation:tf-2.3.0-imz-2.2.0-wide-deep-large-ds-fp32-training
      docs:
      - name: Title
        uri: models/quickstart/recommendation/tensorflow/wide_deep_large_ds/training/fp32/.docs/title.md
      - name: Description
        uri: models/quickstart/recommendation/tensorflow/wide_deep_large_ds/training/fp32/.docs/description.md
      - name: Download link
        uri: models/quickstart/recommendation/tensorflow/wide_deep_large_ds/training/fp32/.docs/download.md
      - name: Datasets
        uri: models/quickstart/recommendation/tensorflow/wide_deep_large_ds/training/fp32/.docs/datasets.md
      - name: Quick Start Scripts
        uri: models/quickstart/recommendation/tensorflow/wide_deep_large_ds/training/fp32/.docs/quickstart.md
      - name: Bare Metal
        uri: models/quickstart/recommendation/tensorflow/wide_deep_large_ds/training/fp32/.docs/baremetal.md
      - name: Docker
        uri: models/quickstart/recommendation/tensorflow/wide_deep_large_ds/training/fp32/.docs/docker.md
      - name: Advanced Options
        uri: models/quickstart/recommendation/tensorflow/wide_deep_large_ds/training/fp32/.docs/advancedoptions.md
      - name: License link
        uri: models/quickstart/recommendation/tensorflow/wide_deep_large_ds/training/fp32/.docs/license.md
