apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wide-deep-large-ds-fp32-training # {"$openapi":"MODEL_NAME"}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
