releases:
  versioned:
    tag_specs:
    - '{ipex-centos-icx-resnet50-base}{icx-resnet50-int8}'
slice_sets:
  icx-resnet50-int8:
  - add_to_name: -icx-resnet50-int8
    args:
    - PACKAGE_NAME=icx-resnet50-int8
    dockerfile_subdirectory: pytorch
    downloads: []
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/ipex-bkc/resnet50-icx/inference/int8/.docs/title.md
        - name: Description
          uri: models/quickstart/ipex-bkc/resnet50-icx/inference/int8/.docs/description.md
        - name: Datasets
          uri: models/quickstart/ipex-bkc/resnet50-icx/inference/int8/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/ipex-bkc/resnet50-icx/inference/int8/.docs/quickstart.md
        - name: Docker
          uri: models/quickstart/ipex-bkc/resnet50-icx/inference/int8/.docs/docker.md
        - name: License
          uri: models/quickstart/ipex-bkc/resnet50-icx/inference/int8/.docs/license.md
        name: README.md
        uri: models/quickstart/ipex-bkc/resnet50-icx/inference/int8
    files:
    - destination: quickstart/inference_throughput.sh
      source: quickstart/ipex-bkc/resnet50-icx/inference/int8/inference_throughput.sh
    - destination: quickstart/inference_realtime.sh
      source: quickstart/ipex-bkc/resnet50-icx/inference/int8/inference_realtime.sh
    - destination: quickstart/inference_accuracy.sh
      source: quickstart/ipex-bkc/resnet50-icx/inference/int8/inference_accuracy.sh
    partials:
    - model_package
    - entrypoint-centos
