apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
subjects:
- kind: ServiceAccount
  name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
