kind: ConfigMap
apiVersion: v1
metadata:
  name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
data:
  DATASET_DIR: /datasets # {"$openapi":"DATASET_DIR"}
  FROZEN_GRAPH: /nfs/root/rfcn-fp32-inference/pretrained_model/rfcn_resnet101_coco_2018_01_28/frozen_inference_graph.pb # {"$openapi":"FROZEN_GRAPH_PATH"}
  FS_ID: "0" # {"$openapi":"FS_ID_VALUE"}
  GROUP_ID: "0" # {"$openapi":"GROUP_ID_VALUE"}
  GROUP_NAME: root # {"$openapi":"GROUP_NAME"}
  OUTPUT_DIR: /nfs/root/rfcn-fp32-inference/output # {"$openapi":"OUTPUT_PATH"}
  PRETRAINED_MODEL_DIR: /nfs/root/rfcn-fp32-inference/pretrained_model # {"$openapi":"PRETRAINED_MODEL_PATH"}
  USER_ID: "0" # {"$openapi":"USER_ID_VALUE"}
  USER_NAME: root # {"$openapi":"USER_NAME"}
  VAL_IMAGE_DIR: /datasets/val2017 # {"$openapi":"VAL_IMAGE_PATH"}
