kind: ConfigMap
apiVersion: v1
metadata:
  name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
data:
  ANNOTATIONS_DIR: /datasets/annotations # {"$openapi":"ANNOTATIONS_DIR"}
  DATASET_DIR: /datasets # {"$openapi":"DATASET_DIR"}
  FS_ID: "0" # {"$openapi":"FS_ID_VALUE"}
  GROUP_ID: "0" # {"$openapi":"GROUP_ID_VALUE"}
  GROUP_NAME: root # {"$openapi":"GROUP_NAME"}
  OUTPUT_DIR: /pvc/root/rfcn-fp32-inference/output # {"$openapi":"OUTPUT_PATH"}
  USER_ID: "0" # {"$openapi":"USER_ID_VALUE"}
  USER_NAME: root # {"$openapi":"USER_NAME"}
  VAL_IMAGE_DIR: /datasets/val2017 # {"$openapi":"VAL_IMAGE_DIR"}
