releases:
  versioned:
    tag_specs:
    - "{_TAG_PREFIX}{intel-tf}{tf-lpot}"
slice_sets:
  tf-lpot:
  - add_to_name: -tf-lpot
    dockerfile_exclusive_name: "-lpot"
    dockerfile_subdirectory: "lpot/tensorflow"
    args:
        - TENSORFLOW_IMAGE=intel/intel-optimized-tensorflow
        - TENSORFLOW_TAG=2.5.0-ubuntu-20.04
        - PY_VERSION=3.8
    partials:
        - python-build
        - lpot/lpot
        - lpot/lpot_source
