releases:
  versioned:
    tag_specs:
    - "{_TAG_PREFIX}{intel-tf}{tf-lpot}{tf-lpot-inceptionv3}"
slice_sets:
  tf-lpot-inceptionv3:
  - add_to_name: -inceptionv3
    dockerfile_subdirectory: lpot/tensorflow
    args:
      - TENSORFLOW_IMAGE=intel/intel-optimized-tensorflow
      - TENSORFLOW_TAG=2.5.0-ubuntu-20.04
      - PY_VERSION=3.8
    partials:
      - wget
      - lpot/tf_inceptionv3
